[build-system]
requires = ["Unreal Engine 5.0.3"]
build-backend = "Unreal Engine"

[project]
name = "GDXR VR Template"
authors = [{name = "Jonathan Bardwell", email = "jonathan.bardwell@gdxr.co.uk"}]
dynamic = ["version", "description"]
