[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GDXR VR Template"
authors = [{name = "Jonathan Bardwell", email = "jonathan.bardwell@gdxr.co.uk"}]
dynamic = ["version", "description"]
